[build]
  command = "npm run build"
  publish = "."

[[redirects]]
  from = "/dashboard.html"
  to = "/dashboard/"
  status = 301

[[redirects]]
  from = "/dashboard"
  to = "/dashboard/"
  status = 301